import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const firaSans = localFont({
  src: "./font/FiraSansCondensed-Regular.ttf",
  variable: "--font-fira-sans",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${firaSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
