import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const firaSans = localFont({
  src: "./font/FiraSansCondensed-Regular.ttf",
  variable: "--font-fira-sans",
  weight: "400",
});

const firaSansLight = localFont({
  src: "./font/FiraSansCondensed-Light.ttf",
  variable: "--font-fira-sans",
  weight: "300",
});

const firaSansSemiBold = localFont({
  src: "./font/FiraSansCondensed-SemiBold.ttf",
  variable: "--font-fira-sans",
  weight: "600",
});

const openSans = localFont({
  src: "./font/OpenSans-Regular.ttf",
  variable: "--font-open-sans",
  weight: "400",
});

const rubicLight = localFont({
  src: "./font/Rubik-Light.ttf",
  variable: "--font-rubic",
  weight: "300",
});

const rubicMedium = localFont({
  src: "./font/Rubik-Medium.ttf",
  variable: "--font-rubic",
  weight: "500",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaSans.variable, firaSansLight.variable, firaSansSemiBold.variable,
        openSans.variable, rubicLight.variable, rubicMedium.variable}`}>
        {children}
      </body>
    </html>
  );
}
